name: rabbitmq-test-sa-4.3

services:
  rabbitmq-43:
    image: rabbitmq:4.3-management
    hostname: rabbitmq-test-43
    container_name: rabbitmq-test-43
    environment:
      RABBITMQ_DEFAULT_USER: lab
      RABBITMQ_DEFAULT_PASS: lab
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins

configs:
  rabbitmq-plugins:
    file: ./rabbitmq-plugins
