name: rabbitmq-test-sa-4.2

services:
  rabbitmq-42:
    image: rabbitmq:4.2-management
    hostname: rabbitmq-test-42
    container_name: rabbitmq-test-42
    environment:
      RABBITMQ_DEFAULT_USER: sdk_test
      RABBITMQ_DEFAULT_PASS: sdk_test
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 10s

configs:
  rabbitmq-plugins:
    file: ./rabbitmq-plugins
